#!/usr/bin/bash

# This bash script is used to run a tool generated by the Lin Lab (https://github.com/linlabcode/pipeline-tools/tree/master/pipeline_tools/scripts)

#This script clusters ChIP H3k27ac region signal and produces a heat map of enhancer regions to aid in identifying clusters of enhancers that are changing in sync. 


cd /storage/cylin/bin/pipeline/
python ~/pipeline/clusterEnhancer.py -d /storage/cylin/grail/projects/Test_aquas/HS_Kronos_CHIP_data_table.txt -i 22rv1_Prostate_Treat_AR,22rv1_Prostate_Treat_FOXA1,22rv1_Prostate_Control_AR,22rv1_Prostate_Control_FOXA1,Pooled_input -r /storage/cylin/grail/projects/Test_aquas/Kronos_prostate_cancer/rose/ -o /storage/cylin/grail/projects/Test_aquas/Kronos_prostate_cancer/clustering/Kronos_AR_FOXA1_0_tss/ -n Kronos_AR_FOXA1_0_tss
